# Generated by Django 5.0.4 on 2024-05-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_product_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_db',
            name='ProductPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
